---
title: "'Workflow: Identification of positions in literature using Thematic Network Analysis"
author: "Withheld until publication"
date: "6/4/2021"
output: pdf_document
---

```{r setup, include=T}
knitr::opts_chunk$set(echo = TRUE)
```
This document shows how to reproduce networks and maps found in xxx. 
```{r libraries and functions, include=T}
library(tm)
library(igraph)
source("functions/backboneExtraction.R")
source("functions/makemap.r")
source("functions/mywordnetwork.r")
```

###Pre-process###
```{r pre-process, include=T}
allTheoretical <-Corpus(DirSource("texts", encoding="UTF-8"), readerControl = list(language="lat")) 
#Perform basic text-mining preprocessing
allTheoretical<-tm_map(allTheoretical,tolower)
allTheoretical<-tm_map(allTheoretical,removePunctuation)
allTheoretical<-tm_map(allTheoretical,stripWhitespace)

source("scripts/substitutions.r")

#These words either provide no meaning or are used so many times that they obscure relevant signals.

wordstoremove<-c(stopwords("english"),"can","also","although","may","maybe","moreover","mostly","onto","per se", "really","therefore","though","thus",
                 "xl011","xl021","xl051","xl071","xn011","xn031","xn051","xn071","xq011","xq031","xq041","xq051","xs021","xs091","xs111","xs121",
                 "2013appendixfp10","20132014","1b","p234","p141")

#Cleaning up..

#allFilesx <- tm_map(allFilesx, removeWords, c("endoffile"))
allTheoretical<-tm_map(allTheoretical,stripWhitespace)
```

###Make Nework###
```{r make network, include=T}
edgelistsTheoretical<-lapply(allTheoretical,myWordNetwork,j.words=wordstoremove)
graphsTheoretical<-list()
for (i in 1:35){
  graphsTheoretical[[i]]<-graph.edgelist(edgelistsTheoretical[[i]],directed=T)
} 

#Bind all excerpts together to a single edge list

allEdgeTheoretical<-rbind(edgelistsTheoretical[[1]],edgelistsTheoretical[[2]],edgelistsTheoretical[[3]],edgelistsTheoretical[[4]],edgelistsTheoretical[[5]],edgelistsTheoretical[[6]],edgelistsTheoretical[[7]],edgelistsTheoretical[[8]],edgelistsTheoretical[[9]],edgelistsTheoretical[[10]],
                        edgelistsTheoretical[[11]],edgelistsTheoretical[[12]],edgelistsTheoretical[[13]],edgelistsTheoretical[[14]],edgelistsTheoretical[[15]],edgelistsTheoretical[[16]],edgelistsTheoretical[[17]],edgelistsTheoretical[[18]],edgelistsTheoretical[[19]],edgelistsTheoretical[[20]],
                        edgelistsTheoretical[[21]],edgelistsTheoretical[[22]],edgelistsTheoretical[[23]],edgelistsTheoretical[[24]],edgelistsTheoretical[[25]],edgelistsTheoretical[[26]],edgelistsTheoretical[[27]],edgelistsTheoretical[[28]],edgelistsTheoretical[[29]],edgelistsTheoretical[[30]],
                        edgelistsTheoretical[[31]],edgelistsTheoretical[[32]],edgelistsTheoretical[[33]],edgelistsTheoretical[[34]],edgelistsTheoretical[[35]])
allNetTheoretical<-graph.edgelist(allEdgeTheoretical,directed=T)
E(allNetTheoretical)$weight<-1
allNetTheoretical<-delete.vertices(allNetTheoretical,v = which(V(allNetTheoretical)$name=="break"))
allNetTheoretical<-simplify(allNetTheoretical,remove.multiple=T,edge.attr.comb=list(weight="sum"))
prT<-page.rank(allNetTheoretical)
V(allNetTheoretical)$pr<-prT$vector
fgT<-fastgreedy.community(as.undirected(allNetTheoretical))
fileNameListOfNodes<-paste("listNodes",format(Sys.time(), "%d%b%Y"),"csv",sep="")
write.csv(V(allNetTheoretical)$name,fileNameListOfNodes)
```

###Create Maps###
```{r make-maps, include=T}
V(allNetTheoretical)$id<-V(allNetTheoretical)$name
freq<-strength(allNetTheoretical,mode = "all")

theoreticalBB<-backboneNetwork(allNetTheoretical,evalFunc = 1, alpha = 0.001)
V(theoreticalBB)$freq<-strength(allNetTheoretical,mode = "all")

####Create a map based on fast-greedy algorithm
fgT<-fastgreedy.community(as.undirected(allNetTheoretical))
fgTBB<-fastgreedy.community(as.undirected(theoreticalBB))

V(theoreticalBB)$fastgreedy<-fgTBB$membership
fileNameTheoreticalBB<-fileNameListOfNodes<-paste("theoretical",format(Sys.time(),"%d%b%Y"),".graphml",sep="")
write.graph(theoreticalBB,fileNameTheoreticalBB,format="graphml")

##MAP CREATION
mapTheoretical<-makemap(fgTBB$membership,theoreticalBB)

mapTBB<-backboneNetwork(mapTheoretical,0.005,1)
V(mapTBB)$n_words<-V(mapTheoretical)$n_words
mapTBB<-decompose.graph(mapTBB)[[1]]
fgMTBB<-fastgreedy.community(as.undirected(mapTBB))
V(mapTBB)$fastgreedy<-fgMTBB$membership
fileNameMapBB<-paste("mapTBB",format(Sys.time(),"%d%b%Y"),".graphml",sep="")
write.graph(theoreticalBB,fileNameMapBB,format="graphml")

mapTheoreticalrem<-delete.vertices(mapTheoretical,1)
mapTremBB<-backboneNetwork(mapTheoreticalrem,0.005,1)
V(mapTremBB)$n_words<-V(mapTheoreticalrem)$n_words
mapTremBB<-decompose.graph(mapTremBB)[[1]]
fgMTremBB<-fastgreedy.community(as.undirected(mapTremBB))
V(mapTremBB)$fastgreedy<-fgMTremBB$membership
fileNameMapTremBB<-paste("mapTremBB",format(Sys.time(),"%d%b%Y"),".graphml",sep="")
write.graph(theoreticalBB,fileNameMapTremBB,format="graphml")

```
###Create theme networkss###
```{r create-theme-networks, include=T}


```
###Output files###
```{r output-files, include=T}
```

###Visual analyses###
